spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              # Set as 'false' since we have the setupRouteConfig()
              enabled: false
              lower-case-service-id: true
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: '*'
                allow-credentials: false
                allowed-methods: '*'
                allowed-headers: '*'

server:
  port: 8072
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_INSTANCE_HOSTNAME:localhost}:8070/eureka/
